### ISSUE TITLE
support querying for nodes based on keys (rather than IDs)

### ISSUE THREAD

**Issue by hartig** [LiUGraphQL/pgschema-to-apischema#33]
Currently, for each type of nodes (as defined by an object type in the SDL), we are creating two query operations: one of which can be used to retrieve a single node based on the ID of that node and the other can be used to retrieve a list of nodes. The aim of this issue is to add a third form of query operations; namely, one that allows users to retrieve a single node based on key attributes as specified by the `@key` directive (see Sec.3.2 in http://olafhartig.de/files/HartigHidders_GRADES2019_Preprint.pdf).

As a simple example, consider the following definition of a Property Graph schema.
```graphql
type User  @key(fields:["login"])  {
   login: String! @required
   nicknames: [String!]!
}
```
The `@key` directive in this example specifies that the `login` property of `User` nodes must be unique (i.e., every `User` node must have a different value for this property). Hence, `login` is a key attribute based on which we can uniquely identify any particular `User` node, which we may also leverage for retrieving nodes via queries in the generate API schema. Therefore, this issue is to extend the tool to generate for every such key an additional query operation in the generated API schema. For the example, this additional query operation would be defined as follows.
```graphql
type Query {
   userByKey( key: _KeyForUser): User
   # ... other query operations here ...
}

input _KeyForUser {
   login: String!
}
```
With this addition it is now possible to write the following query.
```graphql
query {
   userByKey( key: {login: "hartig"} ) {
      nicknames
   }
}
```

A few additional remarks:
* If a key is a composite key, consisting of multiple properties (field names), then these properties must all be in the new input type (that is, the input type named by the pattern `_KeyForXYZ`).
* If a node type has multiple keys, then it is okay for the moment to consider only the first of these keys.

**Comment by rcapshaw** [comment]
For @hartig  or @keski, two questions:

1. When processing the input file, the library that we are using currently neglects to print custom directives when outputting the generated API schema. Is it acceptable for the scope of this ticket for the resulting API schema to lack `key` directives so long as the queries support the keys correctly?
2. Since the key directive isn't natively supported by the library, I had to manually add a directive definition to the input schema. Should it be automatically added? If so, is this an acceptable definition?

> `directive @key(fields: [String!]!) on OBJECT`

**Comment by hartig** [comment]
Riley, you are perfectly right. The definition of that directive was missing in the schema. I have added it now. See the file SpiritContentDB_DB_Schema_Directives.graphql

**Comment by rcapshaw** [comment]
I added a merge request for this change. The current implementation supports a single key annotation with the given format: `@key(fields:["field1", "field2", ...])`. There is currently no validation for whether the fields exist, and the field names must exactly match how they will look once the schema is processed. For example, `SpiritContentDB_DB_Schema_Investigations.graphql` now has :
```
type Authority @key(fields:["name", "position"]) {
  Name: String!
  Position: String!
}
```
Note that the fields are lowercased, since the Authority type in the API schema will have lowercased field names.

The library we are using to parse the schema does not support multiple of the same directives for a single item. If we do end up needing to support multiple keys, one alternative might be to adjust the `fields` parameter to be a list of space-separated field names for each individual key: `@key(fields:["name position", "ssn"]`

**Comment by hartig** [comment]
The PR is #37

**Comment by hartig** [comment]
Thanks for the PR. Please add to the PR the validation for whether the fields exist. I prefer to have such a correctness check. Once you have done so, I will merge the PR. 

We will have to fix the DB schema (I will take care of that).

**Comment by rcapshaw** [comment]
The validation has been added to the PR as requested.

**Comment by hartig** [comment]
Riley, thanks!
I have merged the PR and will close this issue now.
