### ISSUE TITLE
Calling generator.py with --help gives me a syntax error

### ISSUE THREAD

**Issue by hartig** [LiUGraphQL/pgschema-to-apischema#39]
If I execute
```
python3 generator.py --help
```
... I get the following error message:
```
  File "generator.py", line 29
    files.append(f'{args.input}/{filename}')
                                          ^
SyntaxError: invalid syntax
```

The same happens when I try to execute the example command:
```
$ python3 generator.py \
      --input resources/schema.graphql \
      --output api-schema.graphql \
      --config resources/config.yml
```

**Comment by rcapshaw** [comment]
@hartig Because we're using the `f''` style of format strings, it might be the case that your python3 installation needs to be upgraded. Could you verify with `python3 --version` that you have version 3.6 or above installed? When I download everything fresh and run it with version 3.6.10, I get the expected output:
```
optional arguments:
  -h, --help       show this help message and exit
  --input INPUT    GraphQL DB schema files (separated by commas), or a path to
                   a schema directory
  --output OUTPUT  Output schema file (default stdout)
  --config CONFIG  Path to configuration file
```
I'll have to update the README to specify that this is a dependency of the project, since the `graphql-core-next` library requires `Python '>=3.6'`.

**Comment by hartig** [comment]
I have checked:
```bash
$ python3 --version
Python 3.5.2
```
So, indeed, I have only version 3.5.2 of python3. So, I cannot use my laptop to work on this  :-(

...at least, the computer in my office can be used.
